### PR TITLE
feat: Replace the docstring_parser library with Griffe

### PR DESCRIPTION
**Pull request by Masara**
### Summary of Changes
Slowly removing the [docstring_parser](https://github.com/rr-/docstring_parser) library and replacing it with [Griffe](https://github.com/mkdocstrings/griffe).

### CODE REVIEW

**Comment by Masara** [comment]
@lars-reimann Regarding the problem with parsing default values for attributes in docstrings: The specifications of Numpydoc, Google Style Python Docstrings and ReST did not have any information regarding default values for class attributes. Only parameters where defined with default values, which Griffe can analyze. It seems like Griffe adopted the specifications of each style to the point without any extras, therefore it is not able to analyze attribute default values, since they where never specified. I could try to imitate the regex to parse the default values for our case, or what do you think would be best to do?

**Comment by lars-reimann** [comment]
@Masara We don't really need the default value that is listed in the documentation. It might not be valid Python syntax, so always understanding it correctly, might be difficult. We still need to separate it from the type information, though, so we can process that one further.

**Comment by Masara** [comment]
@lars-reimann This is ready for review

**Review by lars-reimann — CHANGES_REQUESTED** [review]

**Review by lars-reimann — APPROVED** [review]
👍

**Pull request merged**
