### PR TITLE
fix: The file structure of stubs resembles the "package" path.

### LINKED ISSUE #81: File structure should mirror package structure
### Is your feature request related to a problem?

Currently, the file structure mirrors the Python implementation, e.g. `data/image/containers/_image/_image.sdsstub`. Note the duplicated `_image`. It should mirror the package structure instead. The leading underscores also serve no purpose in the DSL.

### Desired solution

In the above example, the package is `safeds.data.image.containers`, so the file should be at `data/image/containers/image.sdsstub`. The `_image` folder should be removed, as well as the leading underscore of the file name.

### Possible alternatives (optional)

_No response_

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by Masara**
Closes #81 

### Summary of Changes

Changed how the file structure for stubs is build. Now we follow the "package" path for the structure.

### CODE REVIEW

**Review by lars-reimann — CHANGES_REQUESTED** [review]
Needs automated tests. I'd suggest changing `generate_stubs` to return "virtual files", consisting of a `Path` and a `string` for the content.

Then handle the file I/O in `_run_api_command` (which should be renamed BTW).

Tests can work with the result of `generate_stubs` instead of having to read files from disk again.

**Comment by Masara** [comment]
I refactored a bit here and there like you recommended and there is one test left that calls the `create_stub_files` function (since it also is needed for codecov). Also, I had no idea how to automate the `test_file_creation` test, since I'd have to read all `__init__.py` files of the package and compare package paths etc., which, in the end, would become way too complicated. Or is there maybe a better way, which I can't think of?

**Review by lars-reimann — CHANGES_REQUESTED** [review]
There's still an extra folder being created:

image

**Comment by Masara** [comment]
For me this seems to work correctly, did you delete the old `out` directory before generating new stubs? Also regarding #117, in my `image.sdsstub` I have the package info `package safeds.data.image.containers`, which also seems to be correct...

**Comment by lars-reimann** [comment]
> For me this seems to work correctly, did you delete the old `out` directory before generating new stubs? Also regarding #117, in my `image.sdsstub` I have the package info `package safeds.data.image.containers`, which also seems to be correct...

Yes, and I've checked on two devices, once with Python 3.12 and once with Python 3.11. Using the latest `main` of the library in both cases.

**Comment by lars-reimann** [comment]
> Using the latest `main` of the library in both cases.

@masara That might be the issue: The imports in `__init__` files are now in `TYPE_CHECKING` blocks. We've had to change that to fix the horrendous import times of the library. Maybe that requires a change?

**Comment by Masara** [comment]
I did find and fix a small bug which wouldn't let me parse the latest `main`, but I don't think this bug was related to your issue. Since I can't recreate this I'd say we look at it together next week.

**Comment by lars-reimann** [comment]
@Masara No change in behavior, unfortunately. There's still an extra folder.

**Comment by lars-reimann** [comment]
It works if an absolute path is passed as `-s` argument:

```
safe-ds-stubgen -o "./out" -nc -s "E:/Repositories/safe-ds/Library/src" --docstyle NUMPYDOC -v
```

**Review by lars-reimann — APPROVED** [review]

**Pull request merged**
