### PR TITLE
feat: Rework import generation for stubs.

### LINKED ISSUE #24: feat: Resolve aliasing for imports
### Is your feature request related to a problem?

Currently, import aliases are not resolved.

### Desired solution
In two places in the code aliases have to be recognized and resolved:

1. In the function ```safeds_stubgen.api_analyzer._mypy_helpers.mypy_type_to_abstract_type``` in the part 

```
elif isinstance(mypy_type, mp_types.UnboundType):
    return sds_types.NamedType(name=mypy_type.name)
```

2. In the function ```safeds_stubgen.api_analyzer._ast_visitor.MyPyAstVisitor.enter_classdef``` in the part

```
superclasses = [superclass.fullname for superclass in node.base_type_exprs if hasattr(superclass, "fullname")]
```

You should first look for a function in the mypy library that can resolve types. If such a function does not exist, you'd have to create one yourself. It's possible that such a function can already be found here: ```mypy.fixup.lookup_fully_qualified_alias```

### LINKED ISSUE #38: feat: Rework import generation for stubs.
### Is your feature request related to a problem?

Currently import information are directly taken from the api_analyzer to the stubs generator, but for the stubs we need to check all type hints in the Python code whether the types are new types imported from other files or not. For those new types imports have to be generated and other imports from the api_analyzer do not have to be taken over to the stubs.

### Desired solution

Mypy should be able to specify source paths for type hints, therefore for the first step, those information have to be found and added to the api_analyzer. The second step would be to generate imports for with the stubs generator.

### PR DESCRIPTION
**Pull request by Masara**
Closes #38 
Closes #24 

### Summary of Changes
- Reworked the import generation for Stubs. Imports should now be correctly generated. (#38)
- Aliases are collected with mypy and are now used to resolve alias origins (#24)

#### Other changes
- Added a "// Todo" for the generated Stubs, if an internal class is used as a type.
- Added "// Todo Safe-DS does not support set types" if a set object is used.
- If booleans where used in Literal Types the first letter was capitalized in stubs, which it should not be.
- Removed the "where" part and lower limits of the Stubs for constrains

### CODE REVIEW

**Comment by Masara** [comment]
I realized that changes in this PR clash with what we need from Issue #38. Therefore I will revert this PR to a draft and use it as a PR for issue #38.

**Comment by lars-reimann** [comment]
Yes, probably tomorrow. Could you add a summary of changes?

**Comment by lars-reimann** [comment]
We also need a `syrupy` extension and a `pytest` fixture for stubs (see [this example](https://github.com/Safe-DS/Library/blob/0fb38d252c1596063ddad768d8a0a1e6ad07c1d4/tests/conftest.py#L14)). This way all created stubs get their own file with the correct extension, instead of mushing them all together in on `ambr` file.

**Comment by Masara** [comment]
@lars-reimann I fixed how the import paths are generated for stubs, now it should be correct. There was just one case where I wasn't sure how to handle it: If we have an import from **another** package, how should it look like?
This
```py
@PythonModule("various_modules_package.function_module")
package variousModulesPackage.functionModule

from tests.data.main_package.another_path.another_module import AnotherClass
```

or this
```py
@PythonModule("various_modules_package.function_module")
package variousModulesPackage.functionModule

from mainPackage.AnotherPath.AnotherModule import AnotherClass
```
?

Currently the first case is implemented. If it's correct like this, you can review and hopefully close this PR.

**Comment by lars-reimann** [comment]
The second option is correct, assuming the file containing `AnotherClass` looks something like this:

```
@PythonModule("does not matter for imports in Safe-DS")
package mainPackage.AnotherPath.AnotherModule

class AnotherClass
```

The part between `from` and `import` must always equal to the name of the Safe-DS package you want to import from.

**Comment by Masara** [comment]
@lars-reimann But we are assuming that we did not create the "mainPackage" Stubs yet and don't know where the mainPackage files are. What I concretely mean is, how do imports look like, if we import classes from **other** packages? Packages we perhaps did not create stubs for? The problem here is that we don't know how the package is named, like in the ```tests.data.main_package.another_path.another_module.AnotherClass``` example. Mypy gives us this path to the class, but we actually don't now that "main_package" is the package. Or should I just assume that because our current package, which we are creating stubs for, has the path ```tests.data.out_current_package....``` that we can slice of the ```tests.data``` part for ```tests.data.main_package....```, too?

**Comment by lars-reimann** [comment]
Say we are creating stubs for the package `a` and are currently working on a Python module with the following content:

```py
from b import SomeClass

def f(p: SomeClass)
```

Then we also need to create some stub for the class `SomeClass`, or we can't use it. So limited stubs must be created for the declarations of other packages that package `a` depends on.

**Comment by Masara** [comment]
@lars-reimann If I remove those imports for this PR, what about the types that use the imported classes? Should I removed them, too, for the time being?

**Comment by lars-reimann** [comment]
No, keep the types.

**Comment by Masara** [comment]
@lars-reimann I removed the imports and created issue #66. You can proceed with the PR review.

**Review by lars-reimann — APPROVED** [review]

**Pull request merged**
