### PR TITLE
fix: Fixed the stubs generator

### LINKED ISSUE #80: Cannot create stubs for `safe-ds`
### Describe the bug

Generating stubs for the `safe-ds` library leads to a various errors:

## 1. Error

```txt
Traceback (most recent call last):
  File "C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-stubgen-VELKLkPa-py3.12\Scripts\\safe-ds-stubgen", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\main.py", line 14, in main
    cli()
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 20, in cli
    _run_api_command(args.package, args.src, args.out, args.docstyle, args.testrun, args.naming_convert)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 99, in _run_api_command
    api = get_api(package, src_dir_path, docstring_style, is_test_run)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_get_api.py", line 75, in get_api
    walker.walk(tree)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 30, in walk
    self.__walk(tree, set())
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 77, in __walk
    self.__walk(child_node, visited_nodes)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 42, in __walk
    self.__enter(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 83, in __enter
    method(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 260, in enter_funcdef
    results = self._parse_results(node, function_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 430, in _parse_results
    ret_type = self._infer_type_from_return_stmts(node)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 476, in _infer_type_from_return_stmts
    type_ = mypy_expression_to_sds_type(return_stmt.expr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_mypy_helpers.py", line 105, in mypy_expression_to_sds_type
    raise TypeError("Unexpected expression type.")  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Unexpected expression type.
```

## 2. Error (after no longer raising a type error there)

```txt
Traceback (most recent call last):
  File "C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-stubgen-VELKLkPa-py3.12\Scripts\\safe-ds-stubgen", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\main.py", line 14, in main
    cli()
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 20, in cli
    _run_api_command(args.package, args.src, args.out, args.docstyle, args.testrun, args.naming_convert)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 99, in _run_api_command
    api = get_api(package, src_dir_path, docstring_style, is_test_run)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_get_api.py", line 75, in get_api
    walker.walk(tree)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 30, in walk
    self.__walk(tree, set())
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 77, in __walk
    self.__walk(child_node, visited_nodes)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 77, in __walk
    self.__walk(child_node, visited_nodes)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 42, in __walk
    self.__enter(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 83, in __enter
    method(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 215, in enter_classdef
    is_public=self._is_public(node.name, name),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 1008, in _is_public
    raise TypeError(
TypeError: Expected parent for Writer in module gyp.common to be a class or a module.
```

## 3. Error (after disabling the 2. one)

```txt
Traceback (most recent call last):
  File "C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-stubgen-VELKLkPa-py3.12\Scripts\\safe-ds-stubgen", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\main.py", line 14, in main
    cli()
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 20, in cli
    _run_api_command(args.package, args.src, args.out, args.docstyle, args.testrun, args.naming_convert)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 99, in _run_api_command
    api = get_api(package, src_dir_path, docstring_style, is_test_run)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_get_api.py", line 75, in get_api
    walker.walk(tree)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 30, in walk
    self.__walk(tree, set())
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 77, in __walk
    self.__walk(child_node, visited_nodes)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 77, in __walk
    self.__walk(child_node, visited_nodes)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 77, in __walk
    self.__walk(child_node, visited_nodes)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 42, in __walk
    self.__enter(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 83, in __enter
    method(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 342, in enter_assignmentstmt
    for assignment in self._parse_attributes(lvalue, node.unanalyzed_type, is_static=False):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 563, in _parse_attributes
    assert isinstance(lvalue, mp_nodes.NameExpr | mp_nodes.MemberExpr | mp_nodes.TupleExpr)
AssertionError
```

## 4. Error (after disabling assertion)

```txt
Traceback (most recent call last):
  File "C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-stubgen-VELKLkPa-py3.12\Scripts\\safe-ds-stubgen", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\main.py", line 14, in main
    cli()
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 20, in cli
    _run_api_command(args.package, args.src, args.out, args.docstyle, args.testrun, args.naming_convert)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 99, in _run_api_command
    api = get_api(package, src_dir_path, docstring_style, is_test_run)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_get_api.py", line 75, in get_api
    walker.walk(tree)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 30, in walk
    self.__walk(tree, set())
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 77, in __walk
    self.__walk(child_node, visited_nodes)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 42, in __walk
    self.__enter(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 83, in __enter
    method(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 260, in enter_funcdef
    results = self._parse_results(node, function_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 427, in _parse_results
    ret_type = self.mypy_type_to_abstract_type(node_ret_type, unanalyzed_ret_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 938, in mypy_type_to_abstract_type
    raise ValueError("Unexpected type.")  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unexpected type.
```

## 5. Error (after disabling error 4)

```txt
Traceback (most recent call last):
  File "C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-stubgen-VELKLkPa-py3.12\Scripts\\safe-ds-stubgen", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\main.py", line 14, in main
    cli()
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 20, in cli
    _run_api_command(args.package, args.src, args.out, args.docstyle, args.testrun, args.naming_convert)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 99, in _run_api_command
    api = get_api(package, src_dir_path, docstring_style, is_test_run)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_get_api.py", line 75, in get_api
    walker.walk(tree)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 30, in walk
    self.__walk(tree, set())
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 77, in __walk
    self.__walk(child_node, visited_nodes)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 77, in __walk
    self.__walk(child_node, visited_nodes)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 42, in __walk
    self.__enter(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 83, in __enter
    method(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 252, in enter_funcdef
    arguments = self._parse_parameter_data(node, function_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 715, in _parse_parameter_data
    arg_type = self.mypy_type_to_abstract_type(mypy_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 907, in mypy_type_to_abstract_type
    name, qname = self._find_alias(mypy_type.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 985, in _find_alias
    raise ValueError(f"It was not possible to find out where the alias {type_name} was defined.")
ValueError: It was not possible to find out where the alias np.array was defined.
```

...

### To Reproduce

Used command:

```psh
C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-stubgen-VELKLkPa-py3.12\Scripts\safe-ds-stubgen -p safeds --docstyle NUMPYDOC -o C:\out -nc -v -s E:\Repositories\safe-ds\Library\
```

Versions:

* Python: 3.12.2
* `safe-ds`: Latest main
* `safe-ds-stubgen`: Latest main

### Expected behavior

Stubs should be created.

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by Masara**
Closes #80 

### Summary of Changes
Fixed the stub generator, it should now run with the Library project.

To run the script, use the following command:
`safe-ds-stubgen -p "Library" -o "path/to/out" -nc -s "path/to/Library/src" --docstyle NUMPYDOC`

### CODE REVIEW

**Comment by Masara** [comment]
@lars-reimann The `src.safeds.data.tabular.containers._column.Column.all`, `src.safeds.data.tabular.containers._column.Column.any` and `src.safeds.data.tabular.containers._column.Column.none` methods have `Callable[[T], bool])` as type for the `predicate` parameter. The type is written wrong b/c of the `)` at the end of the type.

**Comment by lars-reimann** [comment]
Feel free to report that in https://github.com/Safe-DS/Library.

**Comment by Masara** [comment]
@lars-reimann Could you merge this next? I need the fixes here for the remaining issue.

**Comment by lars-reimann** [comment]
I'm still getting this error for https://github.com/Safe-DS/Library/commit/e01ad89a58d47be0651c984b33e7865f94397368:

```
...
INFO:root:Working on file ..\library\src\safeds\ml\classical\regression\__init__.py
Traceback (most recent call last):
  File "C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-stubgen-VELKLkPa-py3.12\Scripts\\safe-ds-stubgen", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\main.py", line 14, in main
    cli()
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 20, in cli
    _run_api_command(args.package, args.src, args.out, args.docstyle, args.testrun, args.naming_convert)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 96, in _run_api_command
    api = get_api(package, src_dir_path, docstring_style, is_test_run)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_get_api.py", line 72, in get_api
    walker.walk(tree=tree)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 30, in walk
    self.__walk(tree, set())
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 68, in __walk
    self.__walk(child_node, visited_nodes)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 42, in __walk
    self.__enter(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_walker.py", line 74, in __enter
    method(node)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 264, in enter_funcdef
    results = self._parse_results(node, function_id, result_docstrings)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 446, in _parse_results
    ret_type = self.mypy_type_to_abstract_type(node_ret_type, unanalyzed_ret_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\_ast_visitor.py", line 1004, in mypy_type_to_abstract_type
    raise ValueError("Unexpected type.")  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unexpected type.
```

**Comment by Masara** [comment]
@lars-reimann I removed the raises like you said and instead added the `unknown` type. I also removed the `-p` (package name) argument, since we don't really need it. Could you check again if it works for you?

**Comment by Masara** [comment]
@lars-reimann Could you also chekc the linter error?
```txt
❌ Linted [MARKDOWN] files with [markdown-link-check]: Found 1 error(s) - (3.07s) (expand for details)
  - Using [markdown-link-check v3.11.2] https://megalinter.io/7.10.0/descriptors/markdown_markdown_link_check
  - MegaLinter key: [MARKDOWN_MARKDOWN_LINK_CHECK]
  - Rules config: [/github/workspace/.github/linters/.markdown-link-check.json]
  - Number of files analyzed: [1]
  --Error detail:
  (node:56) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
  (Use `node --trace-deprecation ...` to show where the warning was created)
  
    ERROR: 1 dead links found in docs/README.md !
    [✖] https://dsl.safeds.com/en/stable/language/stub-language/ → Status: 404
```

**Comment by lars-reimann** [comment]
@Masara You can replace the link with `https://dsl.safeds.com/en/stable/stub-language/`.

**Comment by Masara** [comment]
I added a `# pragma: no cover` for the function `safeds_stubgen.api_analyzer._get_api._get_nearest_init_dirs` since I don't know how to test it. The `glob` searches every file and is usually sorted the way we want, but we have to make sure anyway if it's the file we need, since we can't be 100% sure that glob always does what we want. But I can't write tests for test coverage, since the glob sorts the files for us.

**Review by lars-reimann — APPROVED** [review]
Works beautifully now, thank you.

**Pull request merged**
