### PR TITLE
feat: Added handling for sequence classes

### LINKED ISSUE #126: Error when generating stubs for latest version of library
### Describe the bug

The stub generator cannot deal with the return type `Column[R]` of [`Column.transform`](https://github.com/Safe-DS/Library/blob/f08491689552132a2be93bbe923cb15c3010ee54/src/safeds/data/tabular/containers/_column.py#L539).

### To Reproduce

1. Get revision https://github.com/Safe-DS/Library/commit/43717e0431667de6b4da09543240c45c8c3f83ff of the library.
2. Generate stubs for it.

### Expected behavior

Stubs should be generated. In general, the generator should not abort if a few types cannot be understood. It should warn, add `unknown` types and add a TODO to the code instead.

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by Masara**
Closes #126

### Summary of Changes

Added handling for sequence classes and also removed a few "raises" and replaced them with UnknownType's.

### CODE REVIEW

**Comment by lars-reimann** [comment]
Getting this error

```
Traceback (most recent call last):
  File "C:\Users\Lars\AppData\Local\pypoetry\Cache\virtualenvs\safe-ds-stubgen-VELKLkPa-py3.12\Scripts\\safe-ds-stubgen", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\main.py", line 14, in main
    cli()
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 20, in cli
    _run_stub_generator(args.src.resolve(), args.out.resolve(), args.docstyle, args.testrun, args.naming_convert)
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\api_analyzer\cli\_cli.py", line 94, in _run_stub_generator
    stub_data = generate_stub_data(stubs_generator=stubs_generator, out_path=out_dir_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\stubs_generator\_generate_stubs.py", line 67, in generate_stub_data
    module_text, package_info = stubs_generator(module)
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\stubs_generator\_generate_stubs.py", line 188, in __call__
    return self._create_module_string()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\stubs_generator\_generate_stubs.py", line 213, in _create_module_string
    module_text += f"\n{self._create_class_string(class_)}\n"
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\stubs_generator\_generate_stubs.py", line 339, in _create_class_string
    f"{python_name_info}{class_indentation}{self._create_todo_msg(class_indentation)}class "
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repositories\safe-ds\Stub-Generator\src\safeds_stubgen\stubs_generator\_generate_stubs.py", line 1000, in _create_todo_msg
    + {
      ^
KeyError: 'OutputConversion'
```

when running

```
safe-ds-stubgen -o "./out" -nc -s "E:/Repositories/safe-ds/Library/src" --docstyle NUMPYDOC -v
```

on https://github.com/Safe-DS/Library/commit/46f54af61f860ee3790685c330accde1ae4d033f.

**Comment by Masara** [comment]
@lars-reimann It should run now.

**Review by lars-reimann — APPROVED** [review]
Nicely done, thank you.

**Pull request merged**
